# Generated by Django 4.2 on 2025-04-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('bundle', 'Bundle'), ('kg', 'Kilogram'), ('gm', 'Gram'), ('piece', 'Piece')], default='piece', max_length=50),
        ),
    ]
