# Generated by Django 4.2 on 2025-06-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special_offer',
            field=models.TextField(),
        ),
    ]
